version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  auth-service:
    build: ./AuthService
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/auth-service
      - JWT_SECRET=your_jwt_secret_key_here
      # Google OAuth Configuration
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - GOOGLE_CALLBACK_URL=http://localhost:3000/auth/google/callback
      # Facebook OAuth Configuration
      - FACEBOOK_APP_ID=your_facebook_app_id
      - FACEBOOK_APP_SECRET=your_facebook_app_secret
      - FACEBOOK_CALLBACK_URL=http://localhost:3000/auth/facebook/callback
    depends_on:
      - mongodb

  product-service:
    build: ./ProductService
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongodb:27017/product-service
      - JWT_SECRET=your_jwt_secret_key_here
    depends_on:
      - mongodb
      - auth-service

  order-service:
    build: ./OrderService
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://mongodb:27017/order-service
      - JWT_SECRET=your_jwt_secret_key_here
    depends_on:
      - mongodb
      - auth-service
      - product-service

  frontend:
    build: ./Frontend
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_AUTH_SERVICE_URL=http://localhost:3000
      - VUE_APP_PRODUCT_SERVICE_URL=http://localhost:3001
      - VUE_APP_ORDER_SERVICE_URL=http://localhost:3002
      # Add OAuth configuration for frontend
      - VUE_APP_GOOGLE_CLIENT_ID=your_google_client_id
      - VUE_APP_FACEBOOK_APP_ID=your_facebook_app_id
    depends_on:
      - auth-service
      - product-service
      - order-service

volumes:
  mongodb_data: 