version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - ecommerce-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ecommerce-network

  auth-service:
    build: ./AuthService
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URL=mongodb://mongodb-auth:27017/auth
      - JWT_SECRET=your_jwt_secret_key
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb-auth
      - rabbitmq
      - redis
    networks:
      - ecommerce-network

  product-service:
    build: ./ProductService
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URL=mongodb://mongodb-product:27017/product
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb-product
      - rabbitmq
      - redis
    networks:
      - ecommerce-network

  cart-service:
    build: ./CartService
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URL=mongodb://mongodb-cart:27017/cart
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb-cart
      - rabbitmq
      - redis
    networks:
      - ecommerce-network

  order-service:
    build: ./OrderService
    ports:
      - "3004:3004"
    environment:
      - MONGODB_URL=mongodb://mongodb-order:27017/order
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - EMAIL_SERVICE_URL=https://us-central1-precise-valor-457221-a5.cloudfunctions.net/sendOrderConfirmation
    depends_on:
      - mongodb-order
      - rabbitmq
      - redis
    networks:
      - ecommerce-network

  mongodb-auth:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-auth-data:/data/db

  mongodb-product:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb-product-data:/data/db

  mongodb-cart:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongodb-cart-data:/data/db

  mongodb-order:
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - mongodb-order-data:/data/db

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_AUTH_SERVICE_URL=http://localhost:3001
      - REACT_APP_PRODUCT_SERVICE_URL=http://localhost:3002
      - REACT_APP_CART_SERVICE_URL=http://localhost:3003
      - REACT_APP_ORDER_SERVICE_URL=http://localhost:3004
    depends_on:
      - auth-service
      - product-service
      - cart-service
      - order-service
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mongodb-auth-data:
  mongodb-product-data:
  mongodb-cart-data:
  mongodb-order-data:
  rabbitmq-data:
  redis-data: